#!/bin/sh

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"

icon() {
  [ $(cat "$bat/status") = Charging ] && echo "" && exit

  if [ "$per" -gt "90" ]; then
    out=""
  elif [ "$per" -gt "80" ]; then
    out=""
  elif [ "$per" -gt "70" ]; then
    out=""
  elif [ "$per" -gt "60" ]; then
    out=""
  elif [ "$per" -gt "50" ]; then
    out=""
  elif [ "$per" -gt "40" ]; then
    out=""
  elif [ "$per" -gt "30" ]; then
    out=""
  elif [ "$per" -gt "20" ]; then
    out=""
  elif [ "$per" -gt "10" ]; then
    out=""
  elif [ "$per" -gt "0" ]; then
    out=""
  else
    echo ""
  fi

  echo "$out"
}

text() {
  [ $(cat "$bat/status") = Charging ] && echo "$per%" && exit

  if [ "$per" -lt "50" ]; then
    echo "$per%"
  else
    echo ""
  fi
}

class () {
  [ $(cat "$bat/status") = Charging ] && echo "battery_charging" && exit

  if [ "$per" -gt "90" ]; then
    echo "battery_full"
  elif [ "$per" -gt "49" ]; then
    echo "battery_high"
  elif [ "$per" -gt "30" ]; then
    echo "battery_med"
  elif [ "$per" -gt "20" ]; then
    echo "battery_low"
  elif [ "$per" -gt "5" ]; then
    echo "battery_crit"
  else 
    echo "battery_crit"
  fi
}

[ "$1" = "text" ] && text && exit
[ "$1" = "icon" ] && icon && exit
[ "$1" = "class" ] && class && exit
exit

