#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DVI-1 -d 4 5 6 

bspc config border_width         2
bspc config window_gap           15

bspc config focused_border_color  \#b0c9ff
bspc config active_border_color   \#575e8f
bspc config inactive_border_color \#3b4061

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating rectangle=1280x720+1000+300
bspc rule -a Spotify state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a minecraft-launcher state=floating
bspc rule -a Nitrogen state=floating rectangle=600x1200+100+100
bspc rule -a jetbrains-idea-ce state=floating


# Autostart
picom --config ~/.config/i3/picom.conf -b &
nitrogen --restore &
lxsession & # lxsession for polkit support
wmname LG3D # Change window name for java awt support
~/Applications/eww/target/release/eww open leftbar # Launch eww bar
lxappearance & # Weird workaround for mouse cursor
