#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "%{T4}%{T-} Web" "%{T3}%{T-} Dev" "%{T4}%{T-} Shell" "%{T3}%{T-} Art" "%{T3}%{T-} Music" "%{T3}%{T-} Misc"

# bspc monitor -d "" "" "" "" "" ""

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color  \#7A8AAA

bspc config active_border_color   \#282C34
bspc config inactive_border_color \#282C34

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py          focus=on
bspc rule -a Screenkey          manage=off

bspc rule -a Gimp-2.10         state=floating desktop='^4' follow=on
bspc rule -a figma-linux       state=tiled    desktop='^4' follow=on
bspc rule -a figma-linux       state=floating desktop='^4' follow=on
bspc rule -a mplayer2          state=floating desktop='^5'
bspc rule -a Thunar            state=floating
kspc rule -a spotify           state=floating desktop='^5' follow=on
bspc rule -a gnome-calculator  state=floating
bspc rule -a Nitrogen          state=floating
bspc rule -a jetbrains-idea-ce state=floating desktop='^2' follow=on
bspc rule -a code              state=tiled    desktop='^2' follow=on
bspc rule -a Gpick             state=floating
bspc rule -a Chromium-browser  state=tiled    desktop='^1' follow=on
bspc rule -a firefox           state=tiled    desktop='^1' follow=on

# Autostart
nitrogen --restore
dunst &
picom --config ~/.config/bspwm/picom.conf -b
$HOME/.config/polybar/launch.sh

# x stuff
xsetroot -cursor_name left_ptr &
xinput --set-prop 13 320 1
xinput --set-prop 13 328 1
xinput --set-prop 13 340 0.1
# xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &

# Background notification scripts
~/.config/bspwm/battery.sh &


